"""
Frontend Streamlit app: exp8f_streamlit.py
Displays the plots generated by exp8b.py
Run locally: streamlit run exp8f_streamlit.py
"""

import os
import streamlit as st
from exp8b import generate_plots

st.set_page_config(page_title="Exp8 Data Visualizations", layout="wide")
st.title("📊 Experiment 8 – Data Visualization Dashboard")

# Paths
PLOTS_DIR = "exp8_plots"
CSV_PATH = "ScreevsmentalH.csv"

# Generate plots if not already available
if not os.path.exists(PLOTS_DIR) or len(os.listdir(PLOTS_DIR)) == 0:
    st.info("Generating plots from CSV...")
    generate_plots(CSV_PATH)

# Display plots
if os.path.exists(PLOTS_DIR):
    plot_files = sorted([f for f in os.listdir(PLOTS_DIR) if f.endswith(".png")])
    for plot in plot_files:
        st.subheader(plot.replace("_", " ").replace(".png", "").title())
        st.image(os.path.join(PLOTS_DIR, plot))
else:
    st.error("No plots found. Make sure ScreevsmentalH.csv is uploaded and exp8b.py ran successfully.")
